<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Caching\" />
    <Folder Include="Integrations\Mapon\" />
    <Folder Include="Integrations\Bolt\" />
    <Folder Include="Integrations\Uber\" />
    <Folder Include="Messaging\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

</Project>
